name: GitHub Clones Counter

on:
  schedule:
    - cron: '* * * * *' # Roda uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch Clones and Create Badge
        uses: MishaKav/github-badge-clones@v1.0.20
        with:
          create_badge: true
          # O GitHub requer um Token de Acesso Pessoal (PAT) com escopo 'repo' 
          # para ler dados de tráfego, pois o GITHUB_TOKEN padrão não tem essa permissão.
          repository: ${{ github.repository }}
          token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
